CREATE TABLE IF NOT EXISTS User (
	id INT AUTO_INCREMENT,
    username VARCHAR(20) NOT NULL,
    password VARCHAR(30) NOT NULL,
    email VARCHAR(35) NOT NULL,
    forename VARCHAR(25) NOT NULL,
    permissions VARCHAR(15) NOT NULL,
    PRIMARY KEY (id)
) ENGINE = INNODB;

CREATE TABLE IF NOT EXISTS English (
	id INT AUTO_INCREMENT,
    word VARCHAR(25) UNIQUE,
    type VARCHAR(10) NOT NULL,
    PRIMARY KEY (id)
) ENGINE = INNODB;

CREATE TABLE IF NOT EXISTS Welsh (
	id INT AUTO_INCREMENT,
    word VARCHAR(25) UNIQUE,
    gender CHAR(1) NOT NULL,
    type VARCHAR(10) NOT NULL,
    PRIMARY KEY(id)
) ENGINE = INNODB;

CREATE TABLE IF NOT EXISTS Dictionary (
	id INT AUTO_INCREMENT,
    english VARCHAR(25) NOT NULL,
    welsh VARCHAR(25) NOT NULL,
    type VARCHAR(10) NOT NULL, -- allow expansion for verbs, etc.
    PRIMARY KEY(id),
    FOREIGN KEY(english) REFERENCES English(word) ON DELETE CASCADE ON UPDATE CASCADE,
    FOREIGN KEY(welsh) REFERENCES Welsh(word) ON DELETE CASCADE ON UPDATE CASCADE,
    FOREIGN KEY(type) REFERENCES English(type) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE = INNODB;