CREATE TABLE IF NOT EXISTS User (
	user_id INT AUTO_INCREMENT,
    username VARCHAR(20) NOT NULL,
    password VARCHAR(30) NOT NULL,
    email VARCHAR(35) NOT NULL,
    forename VARCHAR(25) NOT NULL,
    permissions VARCHAR(15) NOT NULL,
    PRIMARY KEY (user_id)
) ENGINE = INNODB;

CREATE TABLE IF NOT EXISTS English (
	english_id INT AUTO_INCREMENT,
    word VARCHAR(25) UNIQUE,
    type VARCHAR(10) NOT NULL,
    PRIMARY KEY (english_id)
) ENGINE = INNODB;

CREATE TABLE IF NOT EXISTS Welsh (
	welsh_id INT AUTO_INCREMENT,
    word VARCHAR(25) UNIQUE,
    gender CHAR(1) NOT NULL,
    type VARCHAR(10) NOT NULL,
    PRIMARY KEY(welsh_id)
) ENGINE = INNODB;

/*CREATE TABLE IF NOT EXISTS Dictionary (
	dict_id INT AUTO_INCREMENT,
    english VARCHAR(25) NOT NULL,
    welsh VARCHAR(25) NOT NULL,
    type VARCHAR(10) NOT NULL, -- allow expansion for verbs, etc.
    PRIMARY KEY(dict_id),
    FOREIGN KEY(english) REFERENCES English(word) ON DELETE CASCADE ON UPDATE CASCADE,
    FOREIGN KEY(welsh) REFERENCES Welsh(word) ON DELETE CASCADE ON UPDATE CASCADE,
    FOREIGN KEY(type) REFERENCES English(type) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE = INNODB;*/

CREATE TABLE IF NOT EXISTS Results (
	results_id INT AUTO_INCREMENT,
	user_id INT NOT NULL,
    test_id VARCHAR(20) NOT NULL, -- TODO: reference Test table
	completionDate DATE NOT NULL,
	score INT NOT NULL,
	PRIMARY KEY (results_id),
	FOREIGN KEY (user_id) REFERENCES User (user_id) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE = INNODB;