CREATE TABLE IF NOT EXISTS User (
	user_id INT AUTO_INCREMENT,
    username VARCHAR(20) NOT NULL,
    password VARCHAR(30) NOT NULL,
    email VARCHAR(35) NOT NULL,
    forename VARCHAR(25) NOT NULL,
    permissions VARCHAR(15) NOT NULL,
    PRIMARY KEY (user_id)
) ENGINE = INNODB;

CREATE TABLE IF NOT EXISTS English (
	english_id INT AUTO_INCREMENT,
    word VARCHAR(25) UNIQUE,
    type VARCHAR(10) NOT NULL,
    PRIMARY KEY (english_id)
) ENGINE = INNODB;

CREATE TABLE IF NOT EXISTS Welsh (
	welsh_id INT AUTO_INCREMENT,
    word VARCHAR(25) UNIQUE,
    gender CHAR(1) NOT NULL,
    type VARCHAR(10) NOT NULL,
    PRIMARY KEY(welsh_id)
) ENGINE = INNODB;
